backend:
  name: github
  repo: decidim/decidim.org
  branch: main
media_folder: "source/uploads"
public_folder: "/uploads/"
collections:
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "alert"
        label: "Alert"
        file: "data/alert.yml"
        description: "For changing the contents you need to do it in [GitHub](https://github.com/decidim/decidim.org/blob/main/locales/en.yml) and [Crowdin](https://crowdin.com/project/decidimorg)"
        fields:
          - { label: 'Enabled', name: 'enabled', widget: 'boolean', default: true }
          - { label: 'URL', name: 'url', widget: 'string' }
  - name: "post"
    label: "Post"
    folder: "source/blog/en"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html.md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "select", options: ["releases", "casestudy"]}
  - name: "Installation (usedby)"
    label: "Installation"
    format: yml
    extension: yml
    folder: data/installations/
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "URL", name: "url", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Home Image", name: "home_image", widget: "image"}
      - {label: "Type", name: "type", widget: "select", options: ["city", "org", "region"], required: true}
      - label: "Priority"
        name: "priority"
        widget: "number"
        default: 2
        valueType: "int"
        min: 1
        max: 101
        step: 2
        hint: Larger number is more priority (100 is Barcelona)
      - {label: "Home", name: "home", widget: "boolean", hint: "Is it going to be published on homepage?"}
  - name: "Module"
    label: "Module"
    format: yml
    extension: yml
    folder: data/modules/
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "URL", name: "url", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Type", name: "type", widget: "select", options: ["official", "community", "auth"], required: true}
